-- =========================================================================
-- OFFICEMART 018 — RRHH y nómina: empleados, documentos, marcaciones,
--                  novedades, parámetros versionados y nóminas.
-- =========================================================================
-- ADITIVO. Requiere officemart-000 (y 017 para el bucket privado
-- `documentos`, donde van los archivos de empleados bajo
-- officemart/rrhh/<razon_social_id>/…; las políticas de 017 ya cubren esa
-- carpeta porque solo exigen officemart/<x>/<razon_social_id>).
--
--   empleados: ficha (identidad, puesto, ingreso/salida, salario mensual,
--     frecuencia y forma de pago, afiliaciones, usuario de la app ligado).
--   empleados_documentos: archivos (identidad, contrato…) con vencimiento.
--   rrhh_marcaciones: una fila por empleado y día (entrada, salida, horas).
--   rrhh_novedades: horas extra, bonos, comisiones, aguinaldos, permisos,
--     incapacidades, ausencias, deducciones, anticipos… con banderas
--     gravable (ISR) y cotizable (IHSS/RAP); `nomina_id` cuando se aplican.
--   rrhh_parametros: versión de parámetros legales (IHSS %, techos, RAP,
--     tabla ISR, recargos de horas extra) vigente desde una fecha.
--   rrhh_nominas (+detalle): corrida de nómina Mensual|Quincenal con
--     estados Borrador → Aprobada → Pagada (gasto categoría Nómina) | Anulada.
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.empleados (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id   bigint  NOT NULL,
  codigo            text,
  nombre            text    NOT NULL,
  identidad         text,
  rtn               text,
  fecha_nacimiento  date,
  telefono          text,
  correo            text,
  direccion         text,
  puesto            text,
  departamento      text,
  fecha_ingreso     date,
  fecha_salida      date,
  tipo_contrato     text    NOT NULL DEFAULT 'Permanente',   -- Permanente | Temporal | Por hora
  salario_mensual   numeric(14,2) NOT NULL DEFAULT 0,
  frecuencia_pago   text    NOT NULL DEFAULT 'Mensual',      -- Mensual | Quincenal
  forma_pago        text    NOT NULL DEFAULT 'Transferencia',-- Efectivo | Transferencia
  banco             text,
  cuenta_bancaria   text,
  usuario_id        uuid,                                    -- auth uid del usuario de la app (marcación)
  vendedor_id       bigint,
  ihss_afiliacion   text,
  rap_afiliacion    text,
  aplica_ihss       boolean NOT NULL DEFAULT true,
  aplica_rap        boolean NOT NULL DEFAULT true,
  aplica_isr        boolean NOT NULL DEFAULT true,
  estado            text    NOT NULL DEFAULT 'Activo',       -- Activo | Inactivo
  notas             text,
  usuario           text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz
);
CREATE INDEX IF NOT EXISTS idx_empleados_tenant ON officemart.empleados (razon_social_id, estado, nombre);
ALTER TABLE officemart.empleados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS empleados_tenant ON officemart.empleados;
CREATE POLICY empleados_tenant ON officemart.empleados
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.empleados_documentos (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  empleado_id      bigint  NOT NULL REFERENCES officemart.empleados(id),
  tipo             text    NOT NULL DEFAULT 'Otro',   -- Identidad | Contrato | Certificado | Medico | Otro
  nombre           text    NOT NULL,
  archivo_path     text    NOT NULL,
  vence_en         date,
  notas            text,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_empleados_documentos_emp ON officemart.empleados_documentos (empleado_id);
ALTER TABLE officemart.empleados_documentos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS empleados_documentos_tenant ON officemart.empleados_documentos;
CREATE POLICY empleados_documentos_tenant ON officemart.empleados_documentos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.rrhh_marcaciones (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  empleado_id      bigint  NOT NULL REFERENCES officemart.empleados(id),
  fecha            date    NOT NULL,
  entrada          timestamptz,
  salida           timestamptz,
  horas            numeric(6,2),
  origen           text    NOT NULL DEFAULT 'app',   -- app | manual | import
  notas            text,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz,
  CONSTRAINT rrhh_marcaciones_dia_unq UNIQUE (empleado_id, fecha)
);
CREATE INDEX IF NOT EXISTS idx_rrhh_marcaciones_fecha ON officemart.rrhh_marcaciones (razon_social_id, fecha DESC);
ALTER TABLE officemart.rrhh_marcaciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rrhh_marcaciones_tenant ON officemart.rrhh_marcaciones;
CREATE POLICY rrhh_marcaciones_tenant ON officemart.rrhh_marcaciones
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.rrhh_novedades (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  empleado_id      bigint  NOT NULL REFERENCES officemart.empleados(id),
  tipo             text    NOT NULL,          -- ver TIPOS_NOVEDAD en lib/services/rrhh.ts
  fecha            date    NOT NULL,
  cantidad         numeric(10,2),             -- horas o días según el tipo
  monto            numeric(14,2),             -- monto fijo (bonos, deducciones…)
  gravable         boolean NOT NULL DEFAULT true,   -- entra al ISR
  cotizable        boolean NOT NULL DEFAULT true,   -- entra a IHSS / RAP
  descripcion      text,
  nomina_id        bigint,                    -- nómina en la que se aplicó
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_rrhh_novedades_emp ON officemart.rrhh_novedades (razon_social_id, empleado_id, fecha);
CREATE INDEX IF NOT EXISTS idx_rrhh_novedades_nomina ON officemart.rrhh_novedades (nomina_id);
ALTER TABLE officemart.rrhh_novedades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rrhh_novedades_tenant ON officemart.rrhh_novedades;
CREATE POLICY rrhh_novedades_tenant ON officemart.rrhh_novedades
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.rrhh_parametros (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  vigente_desde    date    NOT NULL,
  nombre           text,
  parametros       jsonb   NOT NULL,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rrhh_parametros_vigencia_unq UNIQUE (razon_social_id, vigente_desde)
);
ALTER TABLE officemart.rrhh_parametros ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rrhh_parametros_tenant ON officemart.rrhh_parametros;
CREATE POLICY rrhh_parametros_tenant ON officemart.rrhh_parametros
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.rrhh_nominas (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id    bigint  NOT NULL,
  tipo               text    NOT NULL DEFAULT 'Mensual',   -- Mensual | Quincenal
  periodo_desde      date    NOT NULL,
  periodo_hasta      date    NOT NULL,
  fecha_pago         date,
  estado             text    NOT NULL DEFAULT 'Borrador',  -- Borrador | Aprobada | Pagada | Anulada
  total_devengado    numeric(14,2) NOT NULL DEFAULT 0,
  total_deducciones  numeric(14,2) NOT NULL DEFAULT 0,
  total_neto         numeric(14,2) NOT NULL DEFAULT 0,
  total_patronal     numeric(14,2) NOT NULL DEFAULT 0,
  parametros_id      bigint,
  gasto_id           bigint,
  notas              text,
  aprobada_at        timestamptz,
  pagada_at          timestamptz,
  anulada_at         timestamptz,
  motivo_anulacion   text,
  usuario            text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz
);
CREATE INDEX IF NOT EXISTS idx_rrhh_nominas_tenant ON officemart.rrhh_nominas (razon_social_id, periodo_hasta DESC);
ALTER TABLE officemart.rrhh_nominas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rrhh_nominas_tenant ON officemart.rrhh_nominas;
CREATE POLICY rrhh_nominas_tenant ON officemart.rrhh_nominas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.rrhh_nominas_detalle (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id    bigint  NOT NULL,
  nomina_id          bigint  NOT NULL REFERENCES officemart.rrhh_nominas(id),
  empleado_id        bigint  NOT NULL REFERENCES officemart.empleados(id),
  empleado_nombre    text    NOT NULL,
  salario_mensual    numeric(14,2) NOT NULL DEFAULT 0,
  dias_periodo       numeric(6,2)  NOT NULL DEFAULT 0,
  dias_no_pagados    numeric(6,2)  NOT NULL DEFAULT 0,
  salario_periodo    numeric(14,2) NOT NULL DEFAULT 0,
  horas_extra        numeric(14,2) NOT NULL DEFAULT 0,
  otros_ingresos     numeric(14,2) NOT NULL DEFAULT 0,
  total_devengado    numeric(14,2) NOT NULL DEFAULT 0,
  ihss_empleado      numeric(14,2) NOT NULL DEFAULT 0,
  rap_empleado       numeric(14,2) NOT NULL DEFAULT 0,
  isr                numeric(14,2) NOT NULL DEFAULT 0,
  otras_deducciones  numeric(14,2) NOT NULL DEFAULT 0,
  total_deducciones  numeric(14,2) NOT NULL DEFAULT 0,
  neto               numeric(14,2) NOT NULL DEFAULT 0,
  ihss_patronal      numeric(14,2) NOT NULL DEFAULT 0,
  rap_patronal       numeric(14,2) NOT NULL DEFAULT 0,
  lineas             jsonb,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_rrhh_nominas_detalle_nomina ON officemart.rrhh_nominas_detalle (nomina_id);
ALTER TABLE officemart.rrhh_nominas_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rrhh_nominas_detalle_tenant ON officemart.rrhh_nominas_detalle;
CREATE POLICY rrhh_nominas_detalle_tenant ON officemart.rrhh_nominas_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- Módulos (categoría RRHH en la app).
INSERT INTO officemart.modulos (nombre) VALUES
  ('Empleados'),
  ('Asistencia'),
  ('Novedades'),
  ('Nómina'),
  ('Parámetros RRHH')
ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
