-- =========================================================================
-- OFFICEMART 011 — Comisiones de vendedores: políticas y liquidaciones.
-- =========================================================================
-- ADITIVO. Requiere officemart-002 (vendedores), 003 (recibos, anulación) y
-- 007 (vista_ventas_reporte: base por categoría/línea).
--
--   politicas_comision: % por vendedor (o todos), sobre venta o utilidad, al
--   facturar o al cobrar, opcionalmente solo para una categoría o línea, con
--   vigencia. La más específica gana (vendedor > categoría/línea > general).
--   comisiones_liquidaciones (+ detalle): cierre de un período por vendedor;
--   al liquidar se crea el gasto "Comisiones" (pagado o pendiente).
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.politicas_comision (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  nombre           text    NOT NULL,
  vendedor_id      bigint,                                  -- NULL = todos los vendedores
  base             text    NOT NULL DEFAULT 'venta',        -- 'venta' | 'utilidad'
  porcentaje       numeric NOT NULL DEFAULT 0,
  categoria_id     bigint,                                  -- solo productos de esta categoría
  linea_id         bigint,                                  -- solo productos de esta línea
  momento          text    NOT NULL DEFAULT 'cobro',        -- 'facturacion' | 'cobro'
  vigente_desde    date,
  vigente_hasta    date,
  activo           boolean NOT NULL DEFAULT true,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz
);
CREATE INDEX IF NOT EXISTS idx_politicas_comision_tenant
  ON officemart.politicas_comision (razon_social_id, activo);
ALTER TABLE officemart.politicas_comision ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS politicas_comision_tenant ON officemart.politicas_comision;
CREATE POLICY politicas_comision_tenant ON officemart.politicas_comision
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.comisiones_liquidaciones (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  vendedor_id      bigint  NOT NULL,
  periodo_desde    date    NOT NULL,
  periodo_hasta    date    NOT NULL,
  total            numeric(14,2) NOT NULL DEFAULT 0,
  estado           text    NOT NULL DEFAULT 'Aprobada',     -- 'Aprobada' | 'Pagada' | 'Anulada'
  gasto_id         bigint,
  notas            text,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz
);
CREATE INDEX IF NOT EXISTS idx_comisiones_liquidaciones_vendedor
  ON officemart.comisiones_liquidaciones (razon_social_id, vendedor_id, periodo_desde);
ALTER TABLE officemart.comisiones_liquidaciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS comisiones_liquidaciones_tenant ON officemart.comisiones_liquidaciones;
CREATE POLICY comisiones_liquidaciones_tenant ON officemart.comisiones_liquidaciones
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.comisiones_liquidaciones_detalle (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  liquidacion_id   bigint  NOT NULL REFERENCES officemart.comisiones_liquidaciones(id) ON DELETE CASCADE,
  venta_id         bigint,
  recibo_id        bigint,
  devolucion_id    bigint,
  fecha            date,
  concepto         text,
  base             numeric(14,2) NOT NULL DEFAULT 0,
  porcentaje       numeric NOT NULL DEFAULT 0,
  monto            numeric(14,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_comisiones_liq_detalle
  ON officemart.comisiones_liquidaciones_detalle (liquidacion_id);
CREATE INDEX IF NOT EXISTS idx_comisiones_liq_detalle_venta
  ON officemart.comisiones_liquidaciones_detalle (razon_social_id, venta_id);
ALTER TABLE officemart.comisiones_liquidaciones_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS comisiones_liquidaciones_detalle_tenant ON officemart.comisiones_liquidaciones_detalle;
CREATE POLICY comisiones_liquidaciones_detalle_tenant ON officemart.comisiones_liquidaciones_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

INSERT INTO officemart.modulos (nombre) VALUES ('Comisiones') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
