-- =========================================================================
-- OFFICEMART 006 — Cotizaciones (presupuestos) con conversión a venta.
-- =========================================================================
-- ADITIVO. Requiere officemart-001 (correlativos, serie COT) y 002/004
-- (vendedores, puntos de facturación: solo referencias lógicas, sin FK).
--
--   cotizaciones_encabezado: número COT-####, cliente (o prospecto por
--   nombre), vendedor, punto, vigencia, estado y totales. `venta_id` se llena
--   al facturarla desde Nueva Venta (estado 'Facturada'); `orden_id` queda
--   reservado para la orden de trabajo (Fase 4.1).
--   cotizaciones_detalle: líneas con producto (opcional: descripción libre),
--   cantidad, precio, % de descuento por línea y subtotal.
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.cotizaciones_encabezado (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id      bigint  NOT NULL,
  numero               text    NOT NULL,                     -- COT-#### (serie 'COT')
  cliente_id           bigint,                               -- NULL = prospecto (solo nombre)
  cliente_nombre       text,                                 -- foto del nombre al cotizar
  vendedor_id          bigint,
  punto_facturacion_id bigint,
  fecha                timestamptz NOT NULL DEFAULT now(),
  vigencia_hasta       date,
  estado               text    NOT NULL DEFAULT 'Borrador',  -- Borrador|Enviada|Aprobada|Facturada|Vencida|Rechazada
  aplica_impuesto      boolean NOT NULL DEFAULT false,
  porcentaje_impuesto  numeric NOT NULL DEFAULT 15,
  descuento            numeric NOT NULL DEFAULT 0,           -- % sobre el subtotal
  subtotal             numeric(14,2) NOT NULL DEFAULT 0,
  impuesto_total       numeric(14,2) NOT NULL DEFAULT 0,
  total                numeric(14,2) NOT NULL DEFAULT 0,
  notas                text,
  condiciones          text,
  motivo_rechazo       text,
  venta_id             bigint,
  orden_id             bigint,
  usuario              text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz,
  CONSTRAINT cotizaciones_numero_unq UNIQUE (razon_social_id, numero)
);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_estado
  ON officemart.cotizaciones_encabezado (razon_social_id, estado, vigencia_hasta);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_cliente
  ON officemart.cotizaciones_encabezado (razon_social_id, cliente_id);
ALTER TABLE officemart.cotizaciones_encabezado ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cotizaciones_encabezado_tenant ON officemart.cotizaciones_encabezado;
CREATE POLICY cotizaciones_encabezado_tenant ON officemart.cotizaciones_encabezado
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.cotizaciones_detalle (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  cotizacion_id    bigint  NOT NULL REFERENCES officemart.cotizaciones_encabezado(id) ON DELETE CASCADE,
  orden            integer NOT NULL DEFAULT 0,
  producto_id      bigint,                                    -- NULL = línea libre
  descripcion      text    NOT NULL,
  cantidad         numeric NOT NULL DEFAULT 1,
  precio_unitario  numeric(14,2) NOT NULL DEFAULT 0,
  descuento_linea  numeric NOT NULL DEFAULT 0,                -- % por línea
  subtotal         numeric(14,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_detalle_cot
  ON officemart.cotizaciones_detalle (cotizacion_id, orden);
ALTER TABLE officemart.cotizaciones_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS cotizaciones_detalle_tenant ON officemart.cotizaciones_detalle;
CREATE POLICY cotizaciones_detalle_tenant ON officemart.cotizaciones_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- Módulo (nace deshabilitado; se habilita por empresa desde /plataforma)
INSERT INTO officemart.modulos (nombre) VALUES ('Cotizaciones') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
