-- =========================================================================
-- OFFICEMART 003 — Anulación de ventas (con estado y motivo), reclamos,
--                  recibos de cobro multi-factura y NC fiscal en devoluciones.
-- =========================================================================
-- ADITIVO. Requiere officemart-001 (auditoria, correlativos) y 002.
--
-- Principio "compensar, no borrar": una venta anulada CONSERVA sus filas y
-- sus asientos originales; la anulación registra contra-asientos (stock,
-- kardex, tesorería) con ref_tipo='anulacion_venta'. Con factura fiscal (CAI)
-- el documento nunca se borra: se anula o se emite nota de crédito.
--
--   1. ventas_encabezado: anulada_at (NULL = vigente), anulada_por, motivo,
--      tipo y reclamo_id. Se usa `anulada_at IS NULL` como filtro de vigentes
--      porque PostgREST `.neq('estado', ...)` excluye los NULL y la regla del
--      proyecto prohíbe defaults en columnas nuevas.
--   2. ventas_reclamos: reclamos del cliente sobre una factura.
--   3. recibos_cobro + pagos_ventas.recibo_id: un recibo (RC-####) cubre
--      varias facturas con UN solo movimiento de tesorería (ref_tipo='recibo').
--   4. devoluciones_encabezado: columnas fiscales (nota de crédito CAI tipo
--      06) y anulación.
--   5. vista_cierre_diario y plataforma_resumen_empresas excluyen anuladas.
--   6. Módulos "Reclamos de Ventas" y "Auditoría".
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. Anulación de ventas
-- -------------------------------------------------------------------------
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS anulada_at       timestamptz;
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS anulada_por      text;
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS motivo_anulacion text;
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS anulacion_tipo   text;   -- 'Anulacion' | 'Reclamo'
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS reclamo_id       bigint;

CREATE INDEX IF NOT EXISTS idx_ventas_encabezado_anulada
  ON officemart.ventas_encabezado (razon_social_id, anulada_at);

-- -------------------------------------------------------------------------
-- 2. Reclamos de ventas
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.ventas_reclamos (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  venta_id        bigint  NOT NULL,
  cliente_id      bigint,
  tipo            text    NOT NULL DEFAULT 'Otro',     -- 'Producto' | 'Precio' | 'Entrega' | 'Otro'
  descripcion     text    NOT NULL,
  estado          text    NOT NULL DEFAULT 'Abierto',  -- 'Abierto' | 'Resuelto' | 'Rechazado'
  resolucion      text,
  resultado       text,                                -- 'Anulacion' | 'Devolucion' | 'Sin cambio'
  devolucion_id   bigint,
  resuelto_at     timestamptz,
  resuelto_por    text,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz
);
CREATE INDEX IF NOT EXISTS idx_ventas_reclamos_venta
  ON officemart.ventas_reclamos (razon_social_id, venta_id);
CREATE INDEX IF NOT EXISTS idx_ventas_reclamos_estado
  ON officemart.ventas_reclamos (razon_social_id, estado);
ALTER TABLE officemart.ventas_reclamos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ventas_reclamos_tenant ON officemart.ventas_reclamos;
CREATE POLICY ventas_reclamos_tenant ON officemart.ventas_reclamos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- -------------------------------------------------------------------------
-- 3. Recibos de cobro (un pago aplicado a varias facturas)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.recibos_cobro (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  numero_recibo    text    NOT NULL,                  -- RC-#### (serie 'RC' de correlativos)
  cliente_id       bigint  NOT NULL,
  fecha            timestamptz NOT NULL DEFAULT now(),
  monto_total      numeric(14,2) NOT NULL,
  metodo_pago      text    NOT NULL,                  -- 'Efectivo' | 'Banco' | 'Otro'
  cuenta_id        bigint,
  referencia       text,                              -- nº transferencia / cheque
  concepto         text,
  anulado_at       timestamptz,
  motivo_anulacion text,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_recibos_cobro_cliente
  ON officemart.recibos_cobro (razon_social_id, cliente_id, fecha DESC);
ALTER TABLE officemart.recibos_cobro ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS recibos_cobro_tenant ON officemart.recibos_cobro;
CREATE POLICY recibos_cobro_tenant ON officemart.recibos_cobro
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- Red de seguridad (misma del script 039): si un recibo se borra físicamente,
-- se va su tesorería. Tabla nueva → trigger nuevo (aditivo).
DROP TRIGGER IF EXISTS trg_tesoreria_recibo ON officemart.recibos_cobro;
CREATE TRIGGER trg_tesoreria_recibo
  AFTER DELETE ON officemart.recibos_cobro
  FOR EACH ROW EXECUTE FUNCTION officemart.tg_limpiar_tesoreria_ref('recibo');

-- Cada abono sabe a qué recibo pertenece (NULL = abono viejo, uno por factura).
ALTER TABLE officemart.pagos_ventas ADD COLUMN IF NOT EXISTS recibo_id bigint;
CREATE INDEX IF NOT EXISTS idx_pagos_ventas_recibo ON officemart.pagos_ventas (recibo_id);

-- -------------------------------------------------------------------------
-- 4. Devoluciones: nota de crédito fiscal (CAI 06) y anulación
-- -------------------------------------------------------------------------
ALTER TABLE officemart.devoluciones_encabezado ADD COLUMN IF NOT EXISTS numero_fiscal         text;
ALTER TABLE officemart.devoluciones_encabezado ADD COLUMN IF NOT EXISTS cai_emitido           text;
ALTER TABLE officemart.devoluciones_encabezado ADD COLUMN IF NOT EXISTS tipo_documento_fiscal text;
ALTER TABLE officemart.devoluciones_encabezado ADD COLUMN IF NOT EXISTS punto_facturacion_id  bigint;
ALTER TABLE officemart.devoluciones_encabezado ADD COLUMN IF NOT EXISTS fiscal_snapshot       jsonb;
ALTER TABLE officemart.devoluciones_encabezado ADD COLUMN IF NOT EXISTS anulada_at            timestamptz;
ALTER TABLE officemart.devoluciones_encabezado ADD COLUMN IF NOT EXISTS motivo_anulacion      text;

-- -------------------------------------------------------------------------
-- 5. Vistas y RPC que agregan ventas
-- -------------------------------------------------------------------------
-- Las vistas `vista_cierre_diario` y `vista_estado_resultados_mensual` NO se
-- tocan: la clonada desde `public` tiene más columnas que el script 013 del
-- repo y `CREATE OR REPLACE VIEW` no puede quitar columnas (error 42P16).
-- Desde este script la app calcula el cierre diario y el P&L directamente
-- desde las tablas (con el filtro `anulada_at IS NULL`) y ya no lee esas
-- vistas, que quedan solo por compatibilidad.

-- Resumen del portal de plataforma (script 037), sin ventas anuladas. Se
-- intenta reemplazar; si la firma clonada difiere, se avisa y no se aborta.
DO $$
BEGIN
  EXECUTE $fn$
  CREATE OR REPLACE FUNCTION officemart.plataforma_resumen_empresas()
  RETURNS TABLE (
    id                bigint,
    nombre            text,
    comercial         text,
    rtn               text,
    usuarios          bigint,
    usuarios_activos  bigint,
    productos         bigint,
    ventas            bigint,
    ingreso_mes       numeric,
    ingreso_total     numeric,
    ultima_venta      timestamptz,
    valor_inventario  numeric,
    creada            timestamptz,
    ultima_conexion   timestamptz
  )
  LANGUAGE sql
  SECURITY DEFINER
  SET search_path = officemart
  AS $body$
    SELECT
      rs.id,
      rs.nombre_empresa,
      rs.nombre_comercial,
      rs.documento,
      (SELECT count(*) FROM officemart.usuarios u WHERE u.razon_social_id = rs.id),
      (SELECT count(*) FROM officemart.usuarios u WHERE u.razon_social_id = rs.id AND u.activo IS NOT FALSE),
      (SELECT count(*) FROM officemart.productos p WHERE p.razon_social_id = rs.id),
      (SELECT count(*) FROM officemart.ventas_encabezado v WHERE v.razon_social_id = rs.id AND v.anulada_at IS NULL),
      (SELECT COALESCE(sum(v.total_venta), 0) FROM officemart.ventas_encabezado v
         WHERE v.razon_social_id = rs.id AND v.anulada_at IS NULL AND v.fecha_venta >= date_trunc('month', now())),
      (SELECT COALESCE(sum(v.total_venta), 0) FROM officemart.ventas_encabezado v
         WHERE v.razon_social_id = rs.id AND v.anulada_at IS NULL),
      (SELECT max(v.fecha_venta) FROM officemart.ventas_encabezado v WHERE v.razon_social_id = rs.id AND v.anulada_at IS NULL),
      (SELECT COALESCE(sum(p.stock_total * p.costo_promedio), 0) FROM officemart.productos p WHERE p.razon_social_id = rs.id),
      (SELECT min(u.created_at) FROM officemart.usuarios u WHERE u.razon_social_id = rs.id),
      (SELECT max(au.last_sign_in_at) FROM officemart.usuarios u JOIN auth.users au ON au.id = u.id WHERE u.razon_social_id = rs.id)
    FROM officemart.razon_social rs
    ORDER BY rs.id;
  $body$
  $fn$;
  REVOKE ALL ON FUNCTION officemart.plataforma_resumen_empresas() FROM PUBLIC;
  GRANT EXECUTE ON FUNCTION officemart.plataforma_resumen_empresas() TO service_role;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'plataforma_resumen_empresas no se reemplazó (%): el portal seguirá contando ventas anuladas.', SQLERRM;
END $$;

-- -------------------------------------------------------------------------
-- 6. Módulos (nacen deshabilitados; se habilitan por empresa desde /plataforma)
-- -------------------------------------------------------------------------
INSERT INTO officemart.modulos (nombre) VALUES ('Reclamos de Ventas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO officemart.modulos (nombre) VALUES ('Auditoría')          ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
