-- =========================================================================
-- OFFICEMART 008 — Recepciones parciales por OC, backorder y cuentas por
--                  pagar por orden de compra (anticipos y abonos).
-- =========================================================================
-- ADITIVO. Requiere officemart-001 (auditoria, tesorería con referencia,
-- tg_limpiar_tesoreria_ref) y 002 (proveedores.dias_credito).
--
--   1. compras_recepciones (+ detalle): cada recepción de una OC es una fila
--      (número 1..n por OC) con sus costos adicionales, tasa y factura del
--      proveedor. La OC acumula lo recibido; lo que falta es backorder.
--   2. compras_pagos: anticipos (antes de recibir) y abonos a una OC, con su
--      movimiento de tesorería (ref_tipo='compra_pago'). Sustituye al gasto
--      "Compra de mercadería" que se creaba al recibir (doble conteo con el
--      CMV en el P&L): desde este script la recepción NO crea gastos.
--   3. compras_encabezado: forma de pago, crédito y vencimiento, montos
--      pagado/recibido, estado de recepción (Sin recibir|Parcial|Completa|
--      Cerrada) y cierre de backorder. `estado` conserva su semántica
--      (Pendiente mientras falte algo, Recibida al completar o cerrar).
--   4. transacciones_inventario.recepcion_id (qué recepción generó la entrada).
--   5. conceptos_gastos.excluir_pyg: gastos que NO van al estado de resultados
--      (se marca "Compra de mercadería": su costo ya está en el CMV).
--   6. RPC incrementar_cantidad_recibida (atómico).
--   7. Módulo "Backorder".
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. Recepciones
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.compras_recepciones (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id           bigint  NOT NULL,
  compra_id                 bigint  NOT NULL,
  numero                    integer NOT NULL DEFAULT 1,          -- 1..n por OC
  fecha                     timestamptz NOT NULL DEFAULT now(),
  almacen_id                bigint,
  localizacion_id           bigint,
  costos_importacion        numeric(14,2) NOT NULL DEFAULT 0,
  impuestos_compra          numeric(14,2) NOT NULL DEFAULT 0,
  otros_costos              numeric(14,2) NOT NULL DEFAULT 0,
  tasa_cambio               numeric(12,4) NOT NULL DEFAULT 1,
  subtotal_local            numeric(14,2) NOT NULL DEFAULT 0,   -- mercancía en L (sin costos extra)
  total_local               numeric(14,2) NOT NULL DEFAULT 0,   -- subtotal_local + costos extra
  numero_factura_proveedor  text,
  notas                     text,
  usuario                   text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT compras_recepciones_numero_unq UNIQUE (compra_id, numero)
);
CREATE INDEX IF NOT EXISTS idx_compras_recepciones_compra
  ON officemart.compras_recepciones (razon_social_id, compra_id);
ALTER TABLE officemart.compras_recepciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS compras_recepciones_tenant ON officemart.compras_recepciones;
CREATE POLICY compras_recepciones_tenant ON officemart.compras_recepciones
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.compras_recepciones_detalle (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id        bigint  NOT NULL,
  recepcion_id           bigint  NOT NULL REFERENCES officemart.compras_recepciones(id) ON DELETE CASCADE,
  compra_detalle_id      bigint,
  producto_id            bigint  NOT NULL,
  cantidad               numeric NOT NULL,
  costo_unitario_origen  numeric(14,4) NOT NULL DEFAULT 0,
  costo_final_local      numeric(14,4) NOT NULL DEFAULT 0,
  precio_venta_aplicado  numeric(14,2)
);
CREATE INDEX IF NOT EXISTS idx_compras_recepciones_detalle_rec
  ON officemart.compras_recepciones_detalle (recepcion_id);
ALTER TABLE officemart.compras_recepciones_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS compras_recepciones_detalle_tenant ON officemart.compras_recepciones_detalle;
CREATE POLICY compras_recepciones_detalle_tenant ON officemart.compras_recepciones_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- -------------------------------------------------------------------------
-- 2. Pagos a órdenes de compra (anticipos y abonos)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.compras_pagos (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  compra_id        bigint  NOT NULL,
  recepcion_id     bigint,
  tipo             text    NOT NULL DEFAULT 'Abono',     -- 'Anticipo' | 'Abono'
  monto            numeric(14,2) NOT NULL,
  metodo           text    NOT NULL,                     -- 'Efectivo' | 'Banco'
  cuenta_id        bigint,
  referencia       text,                                 -- nº transferencia / cheque
  concepto         text,
  fecha            timestamptz NOT NULL DEFAULT now(),
  anulado_at       timestamptz,
  motivo_anulacion text,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_compras_pagos_compra
  ON officemart.compras_pagos (razon_social_id, compra_id);
ALTER TABLE officemart.compras_pagos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS compras_pagos_tenant ON officemart.compras_pagos;
CREATE POLICY compras_pagos_tenant ON officemart.compras_pagos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- Si un pago se borra físicamente, se va su tesorería (misma red del 039).
DROP TRIGGER IF EXISTS trg_tesoreria_compra_pago ON officemart.compras_pagos;
CREATE TRIGGER trg_tesoreria_compra_pago
  AFTER DELETE ON officemart.compras_pagos
  FOR EACH ROW EXECUTE FUNCTION officemart.tg_limpiar_tesoreria_ref('compra_pago');

-- -------------------------------------------------------------------------
-- 3. Encabezado de la OC: crédito, pagos, recepción y cierre (nullable)
-- -------------------------------------------------------------------------
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS forma_pago            text;      -- 'Contado' | 'Credito'
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS dias_credito          integer;
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS fecha_vencimiento     date;
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS monto_pagado          numeric;
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS estado_pago           text;      -- 'Pendiente' | 'Parcial' | 'Pagado'
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS total_recibido_local  numeric;   -- suma de recepciones (L)
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS estado_recepcion      text;      -- 'Sin recibir' | 'Parcial' | 'Completa' | 'Cerrada'
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS cerrada_at            timestamptz;
ALTER TABLE officemart.compras_encabezado ADD COLUMN IF NOT EXISTS motivo_cierre         text;
CREATE INDEX IF NOT EXISTS idx_compras_encabezado_estado_recepcion
  ON officemart.compras_encabezado (razon_social_id, estado_recepcion);

-- -------------------------------------------------------------------------
-- 4. Kardex: qué recepción generó la entrada
-- -------------------------------------------------------------------------
ALTER TABLE officemart.transacciones_inventario ADD COLUMN IF NOT EXISTS recepcion_id bigint;

-- -------------------------------------------------------------------------
-- 5. Conceptos de gasto fuera del P&L (dato: "Compra de mercadería")
-- -------------------------------------------------------------------------
ALTER TABLE officemart.conceptos_gastos ADD COLUMN IF NOT EXISTS excluir_pyg boolean;
UPDATE officemart.conceptos_gastos
   SET excluir_pyg = true
 WHERE lower(nombre) IN ('compra de mercadería', 'compra de mercaderia')
   AND excluir_pyg IS DISTINCT FROM true;

-- -------------------------------------------------------------------------
-- 6. Incremento atómico de cantidad recibida (evita leer-modificar-escribir)
-- -------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION officemart.incrementar_cantidad_recibida(
  p_detalle_id bigint,
  p_delta      numeric
)
RETURNS numeric
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = officemart
AS $$
DECLARE
  v_nueva numeric;
BEGIN
  UPDATE officemart.compras_detalle
     SET cantidad_recibida = COALESCE(cantidad_recibida, 0) + COALESCE(p_delta, 0)
   WHERE id = p_detalle_id
     AND razon_social_id = officemart.app_current_tenant()
  RETURNING cantidad_recibida INTO v_nueva;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'DETALLE_NO_ENCONTRADO: linea % no existe o no es de la empresa', p_detalle_id;
  END IF;
  RETURN v_nueva;
END;
$$;
REVOKE ALL ON FUNCTION officemart.incrementar_cantidad_recibida(bigint, numeric) FROM public;
GRANT EXECUTE ON FUNCTION officemart.incrementar_cantidad_recibida(bigint, numeric) TO authenticated;

-- -------------------------------------------------------------------------
-- 7. Módulo (nace deshabilitado; se habilita por empresa desde /plataforma)
-- -------------------------------------------------------------------------
INSERT INTO officemart.modulos (nombre) VALUES ('Backorder') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
