-- =========================================================================
-- OFFICEMART 014 — Conciliación bancaria: extractos, líneas y pareo con
--                  los movimientos del libro (cuenta_movimientos).
-- =========================================================================
-- ADITIVO. Requiere officemart-001 (cuenta_movimientos.referencia,
-- conciliado_at, extracto_linea_id; movimientos con fecha pasada).
--
--   bancos_formatos_extracto: cómo leer el Excel de cada cuenta (hoja, fila
--   de encabezado, mapeo de columnas, formato de fecha, signo).
--   bancos_extractos: un extracto importado por cuenta y período; al cerrar
--   ('Conciliado') la cuenta queda cerrada hasta `periodo_hasta`
--   (registrarMovimientoCuenta rechaza fechas dentro del período).
--   bancos_extracto_lineas: cada línea del banco con su estado (Pendiente,
--   Conciliada, Ignorada), el movimiento del libro con el que se pareó y cómo
--   (auto, manual, creado).
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.bancos_formatos_extracto (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  cuenta_id        bigint  NOT NULL,
  hoja             text,
  fila_encabezado  integer NOT NULL DEFAULT 1,
  mapeo            jsonb   NOT NULL DEFAULT '{}'::jsonb,   -- {fecha, descripcion, referencia, debito, credito, monto, saldo}
  formato_fecha    text,                                    -- 'DD/MM/YYYY' | 'YYYY-MM-DD' | 'MM/DD/YYYY' | NULL (auto)
  invertir_signo   boolean NOT NULL DEFAULT false,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz,
  CONSTRAINT bancos_formatos_extracto_cuenta_unq UNIQUE (cuenta_id)
);
ALTER TABLE officemart.bancos_formatos_extracto ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bancos_formatos_extracto_tenant ON officemart.bancos_formatos_extracto;
CREATE POLICY bancos_formatos_extracto_tenant ON officemart.bancos_formatos_extracto
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.bancos_extractos (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id      bigint  NOT NULL,
  cuenta_id            bigint  NOT NULL,
  periodo_desde        date    NOT NULL,
  periodo_hasta        date    NOT NULL,
  archivo_nombre       text,
  saldo_inicial_banco  numeric(14,2),
  saldo_final_banco    numeric(14,2),
  estado               text    NOT NULL DEFAULT 'Abierto',   -- 'Abierto' | 'Conciliado'
  conciliado_at        timestamptz,
  conciliado_por       text,
  resumen              jsonb,
  usuario              text,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bancos_extractos_cuenta
  ON officemart.bancos_extractos (razon_social_id, cuenta_id, periodo_hasta DESC);
ALTER TABLE officemart.bancos_extractos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bancos_extractos_tenant ON officemart.bancos_extractos;
CREATE POLICY bancos_extractos_tenant ON officemart.bancos_extractos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.bancos_extracto_lineas (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  extracto_id      bigint  NOT NULL REFERENCES officemart.bancos_extractos(id) ON DELETE CASCADE,
  fila             integer NOT NULL DEFAULT 0,
  fecha            date    NOT NULL,
  descripcion      text,
  referencia       text,
  monto            numeric(14,2) NOT NULL,                  -- + crédito (entra) / − débito (sale)
  saldo_banco      numeric(14,2),
  movimiento_id    bigint,                                  -- cuenta_movimientos.id pareado
  estado           text    NOT NULL DEFAULT 'Pendiente',    -- 'Pendiente' | 'Conciliada' | 'Ignorada'
  metodo_pareo     text,                                    -- 'auto' | 'manual' | 'creado'
  nota             text,
  updated_at       timestamptz
);
CREATE INDEX IF NOT EXISTS idx_bancos_extracto_lineas_ext
  ON officemart.bancos_extracto_lineas (extracto_id, estado);
CREATE INDEX IF NOT EXISTS idx_bancos_extracto_lineas_mov
  ON officemart.bancos_extracto_lineas (movimiento_id);
ALTER TABLE officemart.bancos_extracto_lineas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bancos_extracto_lineas_tenant ON officemart.bancos_extracto_lineas;
CREATE POLICY bancos_extracto_lineas_tenant ON officemart.bancos_extracto_lineas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

INSERT INTO officemart.modulos (nombre) VALUES ('Conciliación Bancaria') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
