-- =========================================================================
-- OFFICEMART 016 — CRM: etapas, contactos, oportunidades y actividades.
-- =========================================================================
-- ADITIVO. Requiere officemart-002 (vendedores). Las FKs a
-- cotizaciones/ventas NO se declaran (officemart-006 puede no estar).
--
--   crm_etapas: columnas del pipeline por empresa (orden, probabilidad %).
--     La app siembra 5 etapas por defecto si la empresa no tiene ninguna.
--   crm_contactos: personas de contacto (de un cliente o prospecto suelto),
--     con cumpleaños para la agenda.
--   crm_oportunidades: negocio en curso (cliente o prospecto), etapa,
--     valor estimado, vendedor, origen, estado Abierta|Ganada|Perdida,
--     cotización/venta vinculada.
--   crm_actividades: llamadas, visitas, reuniones, correos, tareas y notas
--     con fecha programada, resultado y completada (agenda del vendedor).
-- Fechas `fecha` en convención HN-as-UTC (igual que el resto de la app).
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.crm_etapas (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  nombre           text    NOT NULL,
  orden            integer NOT NULL DEFAULT 0,
  probabilidad     integer NOT NULL DEFAULT 0 CHECK (probabilidad BETWEEN 0 AND 100),
  color            text,
  activo           boolean NOT NULL DEFAULT true,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT crm_etapas_nombre_unq UNIQUE (razon_social_id, nombre)
);
ALTER TABLE officemart.crm_etapas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS crm_etapas_tenant ON officemart.crm_etapas;
CREATE POLICY crm_etapas_tenant ON officemart.crm_etapas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.crm_contactos (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  cliente_id       bigint  REFERENCES officemart.clientes(id),
  nombre           text    NOT NULL,
  cargo            text,
  telefono         text,
  correo           text,
  cumpleanos       date,
  notas            text,
  activo           boolean NOT NULL DEFAULT true,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz
);
CREATE INDEX IF NOT EXISTS idx_crm_contactos_cliente
  ON officemart.crm_contactos (razon_social_id, cliente_id);
ALTER TABLE officemart.crm_contactos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS crm_contactos_tenant ON officemart.crm_contactos;
CREATE POLICY crm_contactos_tenant ON officemart.crm_contactos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.crm_oportunidades (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id       bigint  NOT NULL,
  titulo                text    NOT NULL,
  cliente_id            bigint  REFERENCES officemart.clientes(id),
  prospecto_nombre      text,
  contacto_id           bigint  REFERENCES officemart.crm_contactos(id),
  vendedor_id           bigint  REFERENCES officemart.vendedores(id),
  etapa_id              bigint  NOT NULL REFERENCES officemart.crm_etapas(id),
  valor_estimado        numeric(14,2) NOT NULL DEFAULT 0,
  fecha_cierre_esperada date,
  origen                text,
  estado                text    NOT NULL DEFAULT 'Abierta',   -- 'Abierta' | 'Ganada' | 'Perdida'
  motivo_perdida        text,
  cotizacion_id         bigint,
  venta_id              bigint,
  notas                 text,
  cerrada_at            timestamptz,
  usuario               text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz
);
CREATE INDEX IF NOT EXISTS idx_crm_oportunidades_estado
  ON officemart.crm_oportunidades (razon_social_id, estado, etapa_id);
CREATE INDEX IF NOT EXISTS idx_crm_oportunidades_cliente
  ON officemart.crm_oportunidades (razon_social_id, cliente_id);
ALTER TABLE officemart.crm_oportunidades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS crm_oportunidades_tenant ON officemart.crm_oportunidades;
CREATE POLICY crm_oportunidades_tenant ON officemart.crm_oportunidades
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.crm_actividades (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  oportunidad_id   bigint  REFERENCES officemart.crm_oportunidades(id),
  cliente_id       bigint  REFERENCES officemart.clientes(id),
  contacto_id      bigint  REFERENCES officemart.crm_contactos(id),
  vendedor_id      bigint  REFERENCES officemart.vendedores(id),
  tipo             text    NOT NULL DEFAULT 'Tarea',   -- Llamada | Visita | Reunion | Correo | Tarea | Nota
  asunto           text    NOT NULL,
  descripcion      text,
  fecha            timestamptz NOT NULL,
  resultado        text,
  completada       boolean NOT NULL DEFAULT false,
  completada_at    timestamptz,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz
);
CREATE INDEX IF NOT EXISTS idx_crm_actividades_agenda
  ON officemart.crm_actividades (razon_social_id, completada, fecha);
CREATE INDEX IF NOT EXISTS idx_crm_actividades_oportunidad
  ON officemart.crm_actividades (oportunidad_id);
ALTER TABLE officemart.crm_actividades ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS crm_actividades_tenant ON officemart.crm_actividades;
CREATE POLICY crm_actividades_tenant ON officemart.crm_actividades
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- Módulos (categoría CRM en la app).
INSERT INTO officemart.modulos (nombre) VALUES
  ('CRM Pipeline'),
  ('CRM Agenda'),
  ('CRM Reportes')
ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
