-- =========================================================================
-- OFFICEMART 002 — Cimientos: línea de producto, vendedores y zonas, maestro
--                  de clientes y proveedores ampliado.
-- =========================================================================
-- ADITIVO. Requiere officemart-000 y 001.
--
--   T1  `lineas` + `productos.linea_id`: nivel de clasificación adicional
--       (línea de producto) para precios y reportes.
--   T2  `vendedores`, `zonas`, `clientes.vendedor_id/zona_id`,
--       `ventas_encabezado.vendedor_id`: vendedor asociado a cada venta
--       (comisiones, reportes por vendedor/zona) + módulo "Vendedores y Zonas".
--   T3  `clientes`: notas, correo, días de crédito, cliente relacionado
--       (segundo cliente), bloqueo con motivo.
--   T4  `proveedores`: correo, teléfono, dirección, notas, moneda, país, días
--       de crédito.
--
-- Las columnas nuevas sobre tablas existentes son nullable, sin default ni
-- constraint (operación instantánea). Las relaciones (linea_id, zona_id,
-- vendedor_id, cliente_relacionado_id) se resuelven en la app; no se declaran
-- FKs sobre tablas existentes por la misma regla.
-- =========================================================================

-- -------------------------------------------------------------------------
-- T1. Líneas de producto
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.lineas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  nombre          text    NOT NULL,
  descripcion     text,
  activo          boolean NOT NULL DEFAULT true,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_lineas_tenant_nombre
  ON officemart.lineas (razon_social_id, lower(nombre));
ALTER TABLE officemart.lineas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS lineas_tenant ON officemart.lineas;
CREATE POLICY lineas_tenant ON officemart.lineas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

ALTER TABLE officemart.productos ADD COLUMN IF NOT EXISTS linea_id bigint;
CREATE INDEX IF NOT EXISTS idx_productos_linea_id ON officemart.productos (linea_id);

-- -------------------------------------------------------------------------
-- T2. Zonas y vendedores
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.zonas (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  nombre          text    NOT NULL,
  ciudad          text,
  activo          boolean NOT NULL DEFAULT true,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_zonas_tenant_nombre
  ON officemart.zonas (razon_social_id, lower(nombre));
ALTER TABLE officemart.zonas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS zonas_tenant ON officemart.zonas;
CREATE POLICY zonas_tenant ON officemart.zonas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.vendedores (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint  NOT NULL,
  nombre          text    NOT NULL,
  -- Usuario de la app que ES este vendedor (auth.users.id). Opcional: un
  -- vendedor puede no tener acceso al sistema.
  usuario_id      uuid,
  correo          text,
  telefono        text,
  activo          boolean NOT NULL DEFAULT true,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz
);
CREATE INDEX IF NOT EXISTS idx_vendedores_usuario
  ON officemart.vendedores (razon_social_id, usuario_id);
ALTER TABLE officemart.vendedores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS vendedores_tenant ON officemart.vendedores;
CREATE POLICY vendedores_tenant ON officemart.vendedores
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS zona_id     bigint;
ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS vendedor_id bigint;

ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS vendedor_id bigint;
CREATE INDEX IF NOT EXISTS idx_ventas_encabezado_vendedor
  ON officemart.ventas_encabezado (razon_social_id, vendedor_id);

-- Módulo (nace deshabilitado; se habilita por empresa desde /plataforma).
INSERT INTO officemart.modulos (nombre) VALUES ('Vendedores y Zonas')
ON CONFLICT (nombre) DO NOTHING;

-- -------------------------------------------------------------------------
-- T3. Clientes: crédito, contacto y notas
-- -------------------------------------------------------------------------
ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS notas                  text;
ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS correo                 text;
ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS dias_credito           integer;
-- "Segundo cliente": cliente relacionado (a quien se factura / casa matriz).
ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS cliente_relacionado_id bigint;
ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS bloqueado              boolean;
ALTER TABLE officemart.clientes ADD COLUMN IF NOT EXISTS motivo_bloqueo         text;

-- -------------------------------------------------------------------------
-- T4. Proveedores: contacto y condiciones
-- -------------------------------------------------------------------------
ALTER TABLE officemart.proveedores ADD COLUMN IF NOT EXISTS correo       text;
ALTER TABLE officemart.proveedores ADD COLUMN IF NOT EXISTS telefono     text;
ALTER TABLE officemart.proveedores ADD COLUMN IF NOT EXISTS direccion    text;
ALTER TABLE officemart.proveedores ADD COLUMN IF NOT EXISTS notas        text;
ALTER TABLE officemart.proveedores ADD COLUMN IF NOT EXISTS moneda       text;   -- 'LPS' | 'USD'
ALTER TABLE officemart.proveedores ADD COLUMN IF NOT EXISTS pais         text;
ALTER TABLE officemart.proveedores ADD COLUMN IF NOT EXISTS dias_credito integer;

NOTIFY pgrst, 'reload schema';
