-- =========================================================================
-- OFFICEMART 009 — Reposición (mínimos / punto de reorden) y reportes de
--                  compras (estadísticas de OC, estado de cuenta de proveedor).
-- =========================================================================
-- ADITIVO. Requiere officemart-008 (recepciones: lead time real) y 002.
--
--   1. productos_reorden: mínimos y punto de reorden por producto (y
--      opcionalmente por almacén). La sugerencia de compra se calcula en la
--      app con la venta diaria de los últimos 90 días y el lead time real.
--   2. Módulos "Reposición" y "Reportes de Compras" (sin tabla: se calculan
--      desde compras, recepciones, pagos y gastos).
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.productos_reorden (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id    bigint  NOT NULL,
  producto_id        bigint  NOT NULL,
  almacen_id         bigint,                       -- NULL = mínimo global del producto
  stock_minimo       numeric NOT NULL DEFAULT 0,
  punto_reorden      numeric NOT NULL DEFAULT 0,   -- al llegar aquí, comprar
  cantidad_sugerida  numeric,                      -- lote fijo de compra (opcional)
  usuario            text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS productos_reorden_global_unq
  ON officemart.productos_reorden (producto_id) WHERE almacen_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS productos_reorden_almacen_unq
  ON officemart.productos_reorden (producto_id, almacen_id) WHERE almacen_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_productos_reorden_tenant
  ON officemart.productos_reorden (razon_social_id);
ALTER TABLE officemart.productos_reorden ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS productos_reorden_tenant ON officemart.productos_reorden;
CREATE POLICY productos_reorden_tenant ON officemart.productos_reorden
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

INSERT INTO officemart.modulos (nombre) VALUES ('Reposición')          ON CONFLICT (nombre) DO NOTHING;
INSERT INTO officemart.modulos (nombre) VALUES ('Reportes de Compras') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
