-- =========================================================================
-- OFFICEMART 001 — Base común: auditoría, correlativos atómicos, tesorería con
--                  fecha/referencia/conciliación y tipo de referencia en kardex.
-- =========================================================================
-- ADITIVO. Requiere officemart-000 (esquema clonado).
--
-- Lo usan todas las entregas siguientes (anulaciones, recibos, puntos de
-- facturación, cotizaciones, compras, conciliación bancaria):
--   1. `auditoria`: bitácora genérica (quién hizo qué, antes/después).
--   2. `correlativos` + RPC `siguiente_correlativo`: numeración atómica por
--      empresa y serie (RC-, COT-, OT-, DEV-, PED-, series por punto...).
--      Reemplaza los `COUNT(*)+1` que no son seguros con dos usuarios a la vez.
--   3. `cuenta_movimientos`: `referencia` (nº de transferencia/cheque para el
--      pareo bancario), `conciliado_at` y `extracto_linea_id` (conciliación).
--   4. `transacciones_inventario.referencia_tipo`: dice a qué documento apunta
--      `referencia_id` (venta, anulacion_venta, recepcion, orden_produccion...).
--      Las filas viejas quedan NULL y la app sigue infiriendo por tipo_movimiento.
--   5. `tg_limpiar_tesoreria_ref`: la cadena `saldo_resultante` se recalcula
--      por (fecha, id) en vez de solo por id, porque desde ahora un movimiento
--      puede registrarse con fecha pasada (conciliación, saldos iniciales).
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. Auditoría
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.auditoria (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id bigint NOT NULL,
  entidad         text   NOT NULL,      -- 'venta' | 'recibo' | 'compra' | 'orden' | ...
  entidad_id      bigint,
  accion          text   NOT NULL,      -- 'crear' | 'anular' | 'editar' | 'pagar' | ...
  motivo          text,
  antes           jsonb,
  despues         jsonb,
  usuario         text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auditoria_entidad
  ON officemart.auditoria (razon_social_id, entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_fecha
  ON officemart.auditoria (razon_social_id, created_at DESC);

ALTER TABLE officemart.auditoria ENABLE ROW LEVEL SECURITY;
-- La bitácora se lee y se escribe, nunca se edita ni se borra desde la app.
DROP POLICY IF EXISTS auditoria_tenant_select ON officemart.auditoria;
CREATE POLICY auditoria_tenant_select ON officemart.auditoria
  FOR SELECT TO authenticated
  USING (razon_social_id = officemart.app_current_tenant());
DROP POLICY IF EXISTS auditoria_tenant_insert ON officemart.auditoria;
CREATE POLICY auditoria_tenant_insert ON officemart.auditoria
  FOR INSERT TO authenticated
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- -------------------------------------------------------------------------
-- 2. Correlativos atómicos por empresa y serie
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.correlativos (
  razon_social_id bigint NOT NULL,
  serie           text   NOT NULL,      -- 'RC' | 'COT' | 'OT' | 'DEV' | 'PED' | 'venta:<punto>' ...
  ultimo_numero   bigint NOT NULL DEFAULT 0,
  updated_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (razon_social_id, serie)
);

ALTER TABLE officemart.correlativos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS correlativos_tenant ON officemart.correlativos;
CREATE POLICY correlativos_tenant ON officemart.correlativos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- Emite el siguiente número de la serie: el UPSERT toma lock de fila, así dos
-- usuarios simultáneos nunca reciben el mismo número. SECURITY INVOKER: la RLS
-- de `correlativos` garantiza que un usuario solo consume series de su empresa.
-- `p_razon_social_id` es para el service role (rutas públicas sin sesión, p.ej.
-- el pedido por catálogo); un usuario normal no puede usar otro tenant porque
-- la política WITH CHECK lo rechaza.
CREATE OR REPLACE FUNCTION officemart.siguiente_correlativo(
  p_serie text,
  p_prefijo text DEFAULT '',
  p_pad integer DEFAULT 4,
  p_razon_social_id bigint DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = officemart
AS $$
DECLARE
  v_tenant bigint := coalesce(p_razon_social_id, officemart.app_current_tenant());
  v_num    bigint;
BEGIN
  IF v_tenant IS NULL THEN
    RAISE EXCEPTION 'CORRELATIVO_SIN_TENANT: no se pudo resolver la empresa';
  END IF;

  INSERT INTO officemart.correlativos (razon_social_id, serie, ultimo_numero, updated_at)
  VALUES (v_tenant, p_serie, 1, now())
  ON CONFLICT (razon_social_id, serie) DO UPDATE
    SET ultimo_numero = officemart.correlativos.ultimo_numero + 1,
        updated_at    = now()
  RETURNING ultimo_numero INTO v_num;

  RETURN coalesce(p_prefijo, '') || lpad(v_num::text, greatest(coalesce(p_pad, 4), 1), '0');
END;
$$;

REVOKE ALL ON FUNCTION officemart.siguiente_correlativo(text, text, integer, bigint) FROM public;
GRANT EXECUTE ON FUNCTION officemart.siguiente_correlativo(text, text, integer, bigint)
  TO authenticated, service_role;

-- Solo lectura: el número que se emitiría a continuación (para vistas previas).
CREATE OR REPLACE FUNCTION officemart.peek_correlativo(
  p_serie text,
  p_prefijo text DEFAULT '',
  p_pad integer DEFAULT 4,
  p_razon_social_id bigint DEFAULT NULL
)
RETURNS text
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = officemart
AS $$
  SELECT coalesce(p_prefijo, '')
         || lpad((coalesce((SELECT c.ultimo_numero FROM officemart.correlativos c
                            WHERE c.razon_social_id = coalesce(p_razon_social_id, officemart.app_current_tenant())
                              AND c.serie = p_serie), 0) + 1)::text,
                 greatest(coalesce(p_pad, 4), 1), '0');
$$;

REVOKE ALL ON FUNCTION officemart.peek_correlativo(text, text, integer, bigint) FROM public;
GRANT EXECUTE ON FUNCTION officemart.peek_correlativo(text, text, integer, bigint)
  TO authenticated, service_role;

-- Semilla: si ya hay devoluciones/pedidos numerados con COUNT+1, la serie
-- arranca después del máximo existente para no repetir números.
INSERT INTO officemart.correlativos (razon_social_id, serie, ultimo_numero)
SELECT razon_social_id, 'DEV', max(substring(numero_devolucion from '\d+$')::bigint)
FROM officemart.devoluciones_encabezado
WHERE numero_devolucion ~ '^DEV-\d+$' AND razon_social_id IS NOT NULL
GROUP BY razon_social_id
ON CONFLICT (razon_social_id, serie) DO NOTHING;

INSERT INTO officemart.correlativos (razon_social_id, serie, ultimo_numero)
SELECT razon_social_id, 'PED', max(substring(numero_pedido from '\d+$')::bigint)
FROM officemart.pedidos_encabezado
WHERE numero_pedido ~ '^PED-\d+$' AND razon_social_id IS NOT NULL
GROUP BY razon_social_id
ON CONFLICT (razon_social_id, serie) DO NOTHING;

-- -------------------------------------------------------------------------
-- 3. Tesorería: referencia bancaria y marcas de conciliación
-- -------------------------------------------------------------------------
ALTER TABLE officemart.cuenta_movimientos ADD COLUMN IF NOT EXISTS referencia        text;
ALTER TABLE officemart.cuenta_movimientos ADD COLUMN IF NOT EXISTS conciliado_at     timestamptz;
ALTER TABLE officemart.cuenta_movimientos ADD COLUMN IF NOT EXISTS extracto_linea_id bigint;

CREATE INDEX IF NOT EXISTS idx_cuenta_movimientos_cuenta_fecha
  ON officemart.cuenta_movimientos (cuenta_id, fecha, id);

-- -------------------------------------------------------------------------
-- 4. Kardex: tipo de la referencia
-- -------------------------------------------------------------------------
ALTER TABLE officemart.transacciones_inventario ADD COLUMN IF NOT EXISTS referencia_tipo text;

-- -------------------------------------------------------------------------
-- 5. Limpieza de tesorería al borrar el padre: cadena por (fecha, id)
-- -------------------------------------------------------------------------
-- Mismo cuerpo que el script 039 de EasyCount, salvo el ORDER BY de la ventana:
-- desde ahora los movimientos pueden llevar fecha pasada, así que el saldo
-- corriente se acumula en orden cronológico y no en orden de inserción.
-- CREATE OR REPLACE conserva el OID: los triggers existentes siguen apuntando.
CREATE OR REPLACE FUNCTION officemart.tg_limpiar_tesoreria_ref()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = officemart
AS $$
DECLARE
  v_ref_tipo text := TG_ARGV[0];
  v_cuentas  bigint[];
BEGIN
  SELECT array_agg(DISTINCT cuenta_id::bigint) INTO v_cuentas
  FROM officemart.cuenta_movimientos
  WHERE ref_tipo = v_ref_tipo AND ref_id = OLD.id;

  DELETE FROM officemart.caja_chica_movimientos
  WHERE ref_tipo = v_ref_tipo AND ref_id = OLD.id;

  DELETE FROM officemart.cuenta_movimientos
  WHERE ref_tipo = v_ref_tipo AND ref_id = OLD.id;

  IF v_cuentas IS NOT NULL THEN
    WITH r AS (
      SELECT cm.id,
             SUM(CASE WHEN cm.tipo = 'Ingreso' THEN cm.monto ELSE -cm.monto END)
               OVER (PARTITION BY cm.cuenta_id ORDER BY cm.fecha, cm.id
                     ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS s
      FROM officemart.cuenta_movimientos cm
      WHERE cm.cuenta_id = ANY(v_cuentas)
    )
    UPDATE officemart.cuenta_movimientos cm
    SET saldo_resultante = ROUND(r.s, 2)
    FROM r
    WHERE cm.id = r.id
      AND cm.saldo_resultante IS DISTINCT FROM ROUND(r.s, 2);

    UPDATE officemart.cuentas_config c
    SET saldo = COALESCE((
      SELECT ROUND(SUM(CASE WHEN m.tipo = 'Ingreso' THEN m.monto ELSE -m.monto END), 2)
      FROM officemart.cuenta_movimientos m WHERE m.cuenta_id = c.id
    ), 0)
    WHERE c.id = ANY(v_cuentas);
  END IF;

  RETURN OLD;
END;
$$;

NOTIFY pgrst, 'reload schema';
