-- =========================================================================
-- OFFICEMART 017 — Firma digital (firma electrónica simple) de documentos.
-- =========================================================================
-- ADITIVO. Requiere officemart-000.
--
--   documentos_firmados: un PDF enviado a firma (cotización, orden de
--     trabajo, recibo, estado de cuenta, RRHH…) con folio único, hash
--     SHA-256 del original, ruta del PDF original y del PDF estampado.
--   documentos_firmas: cada firmante (interno/externo) con su token único
--     (link público /firmar/<token>), método (canvas|clic), evidencia
--     (fecha, IP, user agent, imagen de la firma) y trazas de envío/visto.
--
--   Storage: bucket PRIVADO `documentos` (compartido con EasyCount); las
--   rutas van bajo officemart/firmas/<razon_social_id>/… y las políticas de
--   storage.objects solo permiten al usuario autenticado leer/subir dentro
--   de la carpeta de su empresa. Las rutas públicas (/api/firma/[token])
--   usan service role y URLs firmadas de corta vida.
--
-- Alcance legal: firma electrónica simple (Decreto 149-2013, Honduras);
-- no es firma certificada por un PSC.
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.documentos_firmados (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id       bigint  NOT NULL,
  folio                 text    NOT NULL,
  entidad               text    NOT NULL,           -- cotizacion | orden_trabajo | recibo | estado_cuenta | rrhh | otro
  entidad_id            bigint,
  titulo                text    NOT NULL,
  hash_sha256           text    NOT NULL,           -- del PDF original
  pdf_original_path     text    NOT NULL,
  pdf_firmado_path      text,
  hash_firmado_sha256   text,
  estado                text    NOT NULL DEFAULT 'Pendiente',   -- Pendiente | Firmado | Anulado | Vencido
  vence_en              timestamptz,
  mensaje               text,
  firmado_at            timestamptz,
  anulado_at            timestamptz,
  motivo_anulacion      text,
  usuario               text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz,
  CONSTRAINT documentos_firmados_folio_unq UNIQUE (folio)
);
CREATE INDEX IF NOT EXISTS idx_documentos_firmados_tenant
  ON officemart.documentos_firmados (razon_social_id, estado, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_documentos_firmados_entidad
  ON officemart.documentos_firmados (razon_social_id, entidad, entidad_id);
ALTER TABLE officemart.documentos_firmados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS documentos_firmados_tenant ON officemart.documentos_firmados;
CREATE POLICY documentos_firmados_tenant ON officemart.documentos_firmados
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.documentos_firmas (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  documento_id     bigint  NOT NULL REFERENCES officemart.documentos_firmados(id),
  orden            integer NOT NULL DEFAULT 1,
  nombre           text    NOT NULL,
  correo           text,
  rol              text    NOT NULL DEFAULT 'externo',   -- interno | externo
  token            text    NOT NULL,                     -- 64 hex, es la autorización del link
  metodo           text,                                 -- canvas | clic
  otp              text,
  otp_vence        timestamptz,
  firmado_en       timestamptz,
  ip               text,
  user_agent       text,
  firma_png_path   text,
  nombre_firmante  text,
  enviado_at       timestamptz,
  visto_at         timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT documentos_firmas_token_unq UNIQUE (token)
);
CREATE INDEX IF NOT EXISTS idx_documentos_firmas_documento
  ON officemart.documentos_firmas (documento_id);
ALTER TABLE officemart.documentos_firmas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS documentos_firmas_tenant ON officemart.documentos_firmas;
CREATE POLICY documentos_firmas_tenant ON officemart.documentos_firmas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- ---------------------------------------------------------------------
-- Storage: bucket privado `documentos` + políticas por carpeta de empresa.
-- Ruta: officemart/firmas/<razon_social_id>/<archivo>
--   storage.foldername(name) = {officemart, firmas, <razon_social_id>}
-- ---------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('documentos', 'documentos', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS officemart_documentos_select ON storage.objects;
CREATE POLICY officemart_documentos_select ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'documentos'
    AND (storage.foldername(name))[1] = 'officemart'
    AND (storage.foldername(name))[3] = officemart.app_current_tenant()::text
  );

DROP POLICY IF EXISTS officemart_documentos_insert ON storage.objects;
CREATE POLICY officemart_documentos_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'documentos'
    AND (storage.foldername(name))[1] = 'officemart'
    AND (storage.foldername(name))[3] = officemart.app_current_tenant()::text
  );

DROP POLICY IF EXISTS officemart_documentos_delete ON storage.objects;
CREATE POLICY officemart_documentos_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'documentos'
    AND (storage.foldername(name))[1] = 'officemart'
    AND (storage.foldername(name))[3] = officemart.app_current_tenant()::text
  );

-- Módulo (bandeja de documentos a firma).
INSERT INTO officemart.modulos (nombre) VALUES ('Firma Digital') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
