-- =========================================================================
-- OFFICEMART 005 — Reglas de precio por categoría / subcategoría / línea en
--                  las listas de precios.
-- =========================================================================
-- ADITIVO. Requiere el esquema clonado (listas_precios, script 042) y
-- officemart-002 (tabla `lineas`).
--
-- Una lista de precios (porcentaje o individual) puede llevar reglas por
-- dimensión: "categoría Papelería −12 %", "línea Escolar −8 %". Al vender,
-- el precio se resuelve con esta precedencia (la primera que aplique):
--   precio individual del producto > subcategoría > categoría > línea >
--   % general de la lista (tipo porcentaje) > precio del maestro.
-- Cada regla apunta a UNA sola dimensión (CHECK) y no se repite (índices
-- únicos parciales). El porcentaje es un DESCUENTO (siempre baja el precio).
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.listas_precios_reglas (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  lista_id         bigint  NOT NULL REFERENCES officemart.listas_precios(id) ON DELETE CASCADE,
  categoria_id     bigint,
  subcategoria_id  bigint,
  linea_id         bigint,
  porcentaje       numeric NOT NULL DEFAULT 0,   -- % de descuento sobre el precio base
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz,
  CONSTRAINT listas_precios_reglas_una_dimension
    CHECK (num_nonnulls(categoria_id, subcategoria_id, linea_id) = 1)
);
CREATE UNIQUE INDEX IF NOT EXISTS listas_precios_reglas_cat_unq
  ON officemart.listas_precios_reglas (lista_id, categoria_id) WHERE categoria_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS listas_precios_reglas_sub_unq
  ON officemart.listas_precios_reglas (lista_id, subcategoria_id) WHERE subcategoria_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS listas_precios_reglas_lin_unq
  ON officemart.listas_precios_reglas (lista_id, linea_id) WHERE linea_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_listas_precios_reglas_lista
  ON officemart.listas_precios_reglas (razon_social_id, lista_id);

ALTER TABLE officemart.listas_precios_reglas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS listas_precios_reglas_tenant ON officemart.listas_precios_reglas;
CREATE POLICY listas_precios_reglas_tenant ON officemart.listas_precios_reglas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

NOTIFY pgrst, 'reload schema';
