-- =========================================================================
-- OFFICEMART 010 — Órdenes de trabajo libres, consumo de materiales/productos
--                  por etapa y costo real de la orden.
-- =========================================================================
-- ADITIVO. Requiere el esquema clonado (scripts 046–058 de producción) y
-- officemart-001 (auditoría).
--
--   1. produccion_ordenes: `tipo` (NULL = Produccion | 'Trabajo'), descripción
--      libre (OT sin producto: `producto_id = 0`, centinela; la columna es NOT
--      NULL y no tiene FK), vínculos a cliente / venta / pedido / cotización y
--      costo real acumulado.
--   2. produccion_orden_etapas.costo_mano_obra: costo de mano de obra que se
--      declara al entregar la etapa.
--   3. produccion_etapa_consumos: materiales O productos consumidos en una
--      etapa (descuentan stock; el producto deja kardex 'Salida Produccion').
--   4. produccion_receta_materiales.operacion_id / producto_id: receta por
--      etapa y con productos (sugeridos; reservado para la UI de recetas).
-- =========================================================================

ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS tipo                   text;      -- NULL = 'Produccion' | 'Trabajo'
ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS descripcion            text;
ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS cliente_id             bigint;
ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS venta_id               bigint;
ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS pedido_id              bigint;
ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS cotizacion_id          bigint;
ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS costo_materiales_real  numeric;
ALTER TABLE officemart.produccion_ordenes ADD COLUMN IF NOT EXISTS costo_total_real       numeric;
CREATE INDEX IF NOT EXISTS idx_produccion_ordenes_tipo
  ON officemart.produccion_ordenes (razon_social_id, tipo);

ALTER TABLE officemart.produccion_orden_etapas ADD COLUMN IF NOT EXISTS costo_mano_obra numeric;

CREATE TABLE IF NOT EXISTS officemart.produccion_etapa_consumos (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  orden_id         bigint  NOT NULL,
  etapa_id         bigint,                                  -- NULL = consumo general de la orden
  tipo_item        text    NOT NULL DEFAULT 'material',     -- 'material' | 'producto'
  material_id      bigint,
  producto_id      bigint,
  cantidad         numeric NOT NULL,
  costo_unitario   numeric(14,4) NOT NULL DEFAULT 0,
  costo_total      numeric(14,2) NOT NULL DEFAULT 0,
  almacen_id       bigint,                                  -- solo producto
  localizacion_id  bigint,                                  -- solo producto
  notas            text,
  fecha            timestamptz NOT NULL DEFAULT now(),
  anulado_at       timestamptz,
  motivo_anulacion text,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT produccion_etapa_consumos_item CHECK (
    (tipo_item = 'material' AND material_id IS NOT NULL) OR
    (tipo_item = 'producto' AND producto_id IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_produccion_etapa_consumos_orden
  ON officemart.produccion_etapa_consumos (razon_social_id, orden_id);
ALTER TABLE officemart.produccion_etapa_consumos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produccion_etapa_consumos_tenant ON officemart.produccion_etapa_consumos;
CREATE POLICY produccion_etapa_consumos_tenant ON officemart.produccion_etapa_consumos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

ALTER TABLE officemart.produccion_receta_materiales ADD COLUMN IF NOT EXISTS operacion_id bigint;
ALTER TABLE officemart.produccion_receta_materiales ADD COLUMN IF NOT EXISTS producto_id  bigint;

NOTIFY pgrst, 'reload schema';
