-- =========================================================================
-- OFFICEMART 020 — Reportería: reportes guardados.
-- =========================================================================
-- ADITIVO. Tabla nueva + RLS + módulo.
--
--   reportes_guardados: configuración de un reporte (fuente, columnas,
--     período —relativo o fijo—, filtros, agrupación, medidas, orden) para
--     volver a exportarlo. El período relativo ("Este mes", "Mes anterior")
--     se recalcula cada vez que se exporta.
--   Módulo "Reportería" (categoría propia en el menú).
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.reportes_guardados (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id      bigint  NOT NULL,
  nombre               text    NOT NULL,
  descripcion          text,
  fuente               text    NOT NULL,
  config               jsonb   NOT NULL,
  favorito             boolean NOT NULL DEFAULT false,
  exportaciones        integer NOT NULL DEFAULT 0,
  ultima_exportacion   timestamptz,
  usuario              text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz
);
CREATE INDEX IF NOT EXISTS idx_reportes_guardados_tenant
  ON officemart.reportes_guardados (razon_social_id, nombre);
ALTER TABLE officemart.reportes_guardados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS reportes_guardados_tenant ON officemart.reportes_guardados;
CREATE POLICY reportes_guardados_tenant ON officemart.reportes_guardados
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

INSERT INTO officemart.modulos (nombre) VALUES ('Reportería') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
