-- =========================================================================
-- OFFICEMART 012 — Consignación: localizaciones de mercancía en consignación
--                  y liquidaciones al proveedor propietario.
-- =========================================================================
-- ADITIVO. Requiere officemart-008 (CxP por OC: la liquidación crea una OC a
-- crédito ya recibida) y 003 (anulación de ventas).
--
--   localizaciones_config.tipo / propietario_proveedor_id: una localización
--   puede ser 'consignacion' (mercancía de un proveedor que solo se paga al
--   venderse). El stock ahí se valora aparte como "consignado".
--   consignacion_liquidaciones (+ detalle): ventas de esa localización en un
--   período, liquidadas al proveedor a costo pactado; genera la OC a crédito.
-- =========================================================================

ALTER TABLE officemart.localizaciones_config ADD COLUMN IF NOT EXISTS tipo                     text;   -- NULL = propia | 'consignacion'
ALTER TABLE officemart.localizaciones_config ADD COLUMN IF NOT EXISTS propietario_proveedor_id bigint;

CREATE TABLE IF NOT EXISTS officemart.consignacion_liquidaciones (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  proveedor_id     bigint  NOT NULL,
  localizacion_id  bigint,
  periodo_desde    date,
  periodo_hasta    date,
  total            numeric(14,2) NOT NULL DEFAULT 0,
  estado           text    NOT NULL DEFAULT 'Aprobada',     -- 'Aprobada' | 'Anulada'
  compra_id        bigint,                                  -- OC a crédito generada (CxP)
  notas            text,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_consignacion_liq_prov
  ON officemart.consignacion_liquidaciones (razon_social_id, proveedor_id);
ALTER TABLE officemart.consignacion_liquidaciones ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS consignacion_liquidaciones_tenant ON officemart.consignacion_liquidaciones;
CREATE POLICY consignacion_liquidaciones_tenant ON officemart.consignacion_liquidaciones
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.consignacion_liquidaciones_detalle (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id   bigint  NOT NULL,
  liquidacion_id    bigint  NOT NULL REFERENCES officemart.consignacion_liquidaciones(id) ON DELETE CASCADE,
  transaccion_id    bigint,                                 -- movimiento 'Salida Venta' liquidado
  venta_id          bigint,
  producto_id       bigint  NOT NULL,
  cantidad          numeric NOT NULL,
  costo_pactado     numeric(14,4) NOT NULL DEFAULT 0,
  monto             numeric(14,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_consignacion_liq_detalle
  ON officemart.consignacion_liquidaciones_detalle (liquidacion_id);
CREATE INDEX IF NOT EXISTS idx_consignacion_liq_detalle_trans
  ON officemart.consignacion_liquidaciones_detalle (razon_social_id, transaccion_id);
ALTER TABLE officemart.consignacion_liquidaciones_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS consignacion_liquidaciones_detalle_tenant ON officemart.consignacion_liquidaciones_detalle;
CREATE POLICY consignacion_liquidaciones_detalle_tenant ON officemart.consignacion_liquidaciones_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

INSERT INTO officemart.modulos (nombre) VALUES ('Consignación') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
