-- =========================================================================
-- OFFICEMART 004 — Puntos de facturación (sucursales) con CAI y serie
--                  interna por punto, y foto fiscal en cada venta.
-- =========================================================================
-- ADITIVO. Requiere officemart-001 (correlativos) y 003 (devoluciones con
-- columnas fiscales).
--
--   1. puntos_facturacion: sucursal/punto de venta (código, nombre, ciudad,
--      dirección, teléfono, localización por defecto, prefijo de serie interna).
--   2. usuarios.punto_facturacion_id: punto asignado a cada usuario.
--   3. facturacion_cai_puntos: la misma configuración CAI de
--      `facturacion_cai_config` pero por punto (punto 0 = empresa sin puntos).
--      Se siembra desde la tabla vieja, que queda de solo lectura.
--   4. ventas_encabezado.punto_facturacion_id / localizacion_id /
--      fiscal_snapshot: la venta guarda su punto, la localización real desde
--      la que salió y una FOTO de la autorización CAI usada (CAI, rango,
--      fecha límite, imprenta) para reimprimir igual aunque cambie el CAI.
--   5. RPC siguiente_correlativo_cai_v2 / peek_correlativo_cai_v2 (tipo +
--      punto) sobre la tabla nueva; los RPC viejos siguen existiendo.
--   6. Módulo "Puntos de Facturación".
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. Puntos de facturación
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.puntos_facturacion (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  codigo           text    NOT NULL,                 -- 'SPS', 'TGU', 'CEIBA'
  nombre           text    NOT NULL,
  ciudad           text,
  direccion        text,
  telefono         text,
  localizacion_id  bigint,                           -- localización (almacén) por defecto
  serie_prefijo    text,                             -- 'FC-SPS-' → serie interna propia; NULL = FC-#### global
  activo           boolean NOT NULL DEFAULT true,
  usuario          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz,
  CONSTRAINT puntos_facturacion_codigo_unq UNIQUE (razon_social_id, codigo)
);
ALTER TABLE officemart.puntos_facturacion ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS puntos_facturacion_tenant ON officemart.puntos_facturacion;
CREATE POLICY puntos_facturacion_tenant ON officemart.puntos_facturacion
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- -------------------------------------------------------------------------
-- 2. Punto asignado al usuario (lo administra el admin de la empresa)
-- -------------------------------------------------------------------------
ALTER TABLE officemart.usuarios ADD COLUMN IF NOT EXISTS punto_facturacion_id bigint;

-- -------------------------------------------------------------------------
-- 3. Configuración CAI por punto y tipo de documento
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS officemart.facturacion_cai_puntos (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id      bigint  NOT NULL,
  punto_facturacion_id bigint  NOT NULL DEFAULT 0,   -- 0 = empresa sin puntos
  tipo_documento       text    NOT NULL DEFAULT '01',
  cai                  text,
  establecimiento      text    NOT NULL DEFAULT '000',
  punto_emision        text    NOT NULL DEFAULT '001',
  rango_inicial        bigint  NOT NULL DEFAULT 1,
  rango_final          bigint  NOT NULL DEFAULT 0,
  correlativo_actual   bigint  NOT NULL DEFAULT 1,
  fecha_limite_emision date,
  imprenta_nombre      text,
  imprenta_rtn         text,
  imprenta_registro    text,
  activo               boolean NOT NULL DEFAULT true,
  usuario              text,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT facturacion_cai_puntos_unq UNIQUE (razon_social_id, punto_facturacion_id, tipo_documento)
);
ALTER TABLE officemart.facturacion_cai_puntos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS facturacion_cai_puntos_tenant ON officemart.facturacion_cai_puntos;
CREATE POLICY facturacion_cai_puntos_tenant ON officemart.facturacion_cai_puntos
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- Semilla: lo que ya estaba configurado pasa como "punto 0". Idempotente.
INSERT INTO officemart.facturacion_cai_puntos (
  razon_social_id, punto_facturacion_id, tipo_documento, cai, establecimiento,
  punto_emision, rango_inicial, rango_final, correlativo_actual,
  fecha_limite_emision, imprenta_nombre, imprenta_rtn, imprenta_registro,
  activo, usuario, created_at, updated_at
)
SELECT
  c.razon_social_id, 0, c.tipo_documento, c.cai, c.establecimiento,
  c.punto_emision, c.rango_inicial, c.rango_final, c.correlativo_actual,
  c.fecha_limite_emision, c.imprenta_nombre, c.imprenta_rtn, c.imprenta_registro,
  c.activo, c.usuario, c.created_at, c.updated_at
FROM officemart.facturacion_cai_config c
ON CONFLICT (razon_social_id, punto_facturacion_id, tipo_documento) DO NOTHING;

-- -------------------------------------------------------------------------
-- 4. La venta guarda su punto, localización y foto fiscal
-- -------------------------------------------------------------------------
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS punto_facturacion_id bigint;
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS localizacion_id      bigint;
ALTER TABLE officemart.ventas_encabezado ADD COLUMN IF NOT EXISTS fiscal_snapshot      jsonb;
CREATE INDEX IF NOT EXISTS idx_ventas_encabezado_punto
  ON officemart.ventas_encabezado (razon_social_id, punto_facturacion_id);

-- -------------------------------------------------------------------------
-- 5. Correlativo fiscal por punto (mismo cuerpo del script 063, tabla nueva)
-- -------------------------------------------------------------------------
-- Devuelve además el rango, la fecha límite y la imprenta para que la app
-- arme la foto fiscal sin otra consulta.
CREATE OR REPLACE FUNCTION officemart.siguiente_correlativo_cai_v2(
  p_tipo_documento text DEFAULT '01',
  p_punto_id       bigint DEFAULT 0
)
RETURNS TABLE (
  numero               text,
  correlativo          bigint,
  establecimiento      text,
  punto_emision        text,
  tipo_documento       text,
  cai                  text,
  rango_inicial        bigint,
  rango_final          bigint,
  fecha_limite_emision date,
  imprenta_nombre      text,
  imprenta_rtn         text,
  imprenta_registro    text
)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = officemart
AS $$
DECLARE
  v_row  officemart.facturacion_cai_puntos%ROWTYPE;
  v_next bigint;
BEGIN
  -- Lock de la fila del tenant para este punto y tipo (RLS ya la aísla).
  -- Columnas calificadas: `tipo_documento` también es columna de salida (42702).
  SELECT * INTO v_row
  FROM officemart.facturacion_cai_puntos
  WHERE facturacion_cai_puntos.tipo_documento = p_tipo_documento
    AND facturacion_cai_puntos.punto_facturacion_id = COALESCE(p_punto_id, 0)
    AND facturacion_cai_puntos.razon_social_id = officemart.app_current_tenant()
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'CAI_CONFIG_MISSING: no hay configuracion CAI para el tipo % en el punto %',
      p_tipo_documento, COALESCE(p_punto_id, 0);
  END IF;
  IF NOT v_row.activo THEN
    RAISE EXCEPTION 'CAI_CONFIG_INACTIVE: la autorizacion CAI del tipo % (punto %) esta inactiva',
      p_tipo_documento, COALESCE(p_punto_id, 0);
  END IF;

  v_next := v_row.correlativo_actual;
  IF v_next < v_row.rango_inicial THEN
    v_next := v_row.rango_inicial;
  END IF;
  IF v_row.rango_final > 0 AND v_next > v_row.rango_final THEN
    RAISE EXCEPTION 'CAI_RANGE_EXHAUSTED: se agoto el rango autorizado (% al %)',
      v_row.rango_inicial, v_row.rango_final;
  END IF;

  UPDATE officemart.facturacion_cai_puntos
  SET correlativo_actual = v_next + 1,
      updated_at = now()
  WHERE id = v_row.id;

  numero := lpad(coalesce(v_row.establecimiento,'000'), 3, '0')
    || '-' || lpad(coalesce(v_row.punto_emision,'001'), 3, '0')
    || '-' || lpad(coalesce(v_row.tipo_documento,'01'), 2, '0')
    || '-' || lpad(v_next::text, 8, '0');
  correlativo          := v_next;
  establecimiento      := v_row.establecimiento;
  punto_emision        := v_row.punto_emision;
  tipo_documento       := v_row.tipo_documento;
  cai                  := v_row.cai;
  rango_inicial        := v_row.rango_inicial;
  rango_final          := v_row.rango_final;
  fecha_limite_emision := v_row.fecha_limite_emision;
  imprenta_nombre      := v_row.imprenta_nombre;
  imprenta_rtn         := v_row.imprenta_rtn;
  imprenta_registro    := v_row.imprenta_registro;
  RETURN NEXT;
END;
$$;
REVOKE ALL ON FUNCTION officemart.siguiente_correlativo_cai_v2(text, bigint) FROM public;
GRANT EXECUTE ON FUNCTION officemart.siguiente_correlativo_cai_v2(text, bigint) TO authenticated;

CREATE OR REPLACE FUNCTION officemart.peek_correlativo_cai_v2(
  p_tipo_documento text DEFAULT '01',
  p_punto_id       bigint DEFAULT 0
)
RETURNS text
LANGUAGE sql
SECURITY INVOKER
SET search_path = officemart
AS $$
  SELECT lpad(coalesce(establecimiento,'000'), 3, '0')
    || '-' || lpad(coalesce(punto_emision,'001'), 3, '0')
    || '-' || lpad(coalesce(tipo_documento,'01'), 2, '0')
    || '-' || lpad(greatest(correlativo_actual, rango_inicial)::text, 8, '0')
  FROM officemart.facturacion_cai_puntos
  WHERE tipo_documento = p_tipo_documento
    AND punto_facturacion_id = COALESCE(p_punto_id, 0)
    AND razon_social_id = officemart.app_current_tenant()
    AND activo = true;
$$;
REVOKE ALL ON FUNCTION officemart.peek_correlativo_cai_v2(text, bigint) FROM public;
GRANT EXECUTE ON FUNCTION officemart.peek_correlativo_cai_v2(text, bigint) TO authenticated;

-- -------------------------------------------------------------------------
-- 6. Módulo (nace deshabilitado; se habilita por empresa desde /plataforma)
-- -------------------------------------------------------------------------
INSERT INTO officemart.modulos (nombre) VALUES ('Puntos de Facturación') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
