-- =========================================================================
-- OFFICEMART 013 — Toma física de inventario con congelamiento por almacén.
-- =========================================================================
-- ADITIVO. Requiere el esquema clonado (transacciones_inventario,
-- vista_stock_por_localizacion) y officemart-001 (auditoría).
--
--   tomas_fisicas: una toma por almacén; al ABRIRLA se congela el almacén
--   (ningún movimiento de inventario entra mientras esté 'Abierta') y se
--   fotografía el stock por localización en el detalle. Al CERRARLA se aplican
--   los ajustes por diferencia (kardex 'Ajuste') con motivo "Toma física #N".
--   La función inventario_congelado(almacen) la consulta la app antes de
--   vender / recibir / trasladar / ajustar, y el trigger sobre
--   transacciones_inventario es la red de seguridad. El cierre pasa la toma a
--   'Cerrada' ANTES de insertar los ajustes, por lo que el trigger no los frena.
-- =========================================================================

CREATE TABLE IF NOT EXISTS officemart.tomas_fisicas (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id    bigint  NOT NULL,
  almacen_id         bigint  NOT NULL,
  estado             text    NOT NULL DEFAULT 'Abierta',   -- 'Abierta' | 'Cerrada' | 'Cancelada'
  fecha_congelacion  timestamptz NOT NULL DEFAULT now(),
  fecha_cierre       timestamptz,
  notas              text,
  total_faltante     numeric(14,2),
  total_sobrante     numeric(14,2),
  lineas_ajustadas   integer,
  usuario            text,
  cerrada_por        text,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tomas_fisicas_almacen_estado
  ON officemart.tomas_fisicas (razon_social_id, almacen_id, estado);
ALTER TABLE officemart.tomas_fisicas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tomas_fisicas_tenant ON officemart.tomas_fisicas;
CREATE POLICY tomas_fisicas_tenant ON officemart.tomas_fisicas
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

CREATE TABLE IF NOT EXISTS officemart.tomas_fisicas_detalle (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social_id  bigint  NOT NULL,
  toma_id          bigint  NOT NULL REFERENCES officemart.tomas_fisicas(id) ON DELETE CASCADE,
  producto_id      bigint  NOT NULL,
  localizacion_id  bigint  NOT NULL,
  stock_sistema    numeric NOT NULL DEFAULT 0,
  conteo           numeric,                                  -- NULL = sin contar
  diferencia       numeric,                                  -- conteo − sistema (al contar)
  costo_unitario   numeric(14,4) NOT NULL DEFAULT 0,
  contado_por      text,
  updated_at       timestamptz,
  CONSTRAINT tomas_fisicas_detalle_unq UNIQUE (toma_id, producto_id, localizacion_id)
);
CREATE INDEX IF NOT EXISTS idx_tomas_fisicas_detalle_toma
  ON officemart.tomas_fisicas_detalle (toma_id);
ALTER TABLE officemart.tomas_fisicas_detalle ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tomas_fisicas_detalle_tenant ON officemart.tomas_fisicas_detalle;
CREATE POLICY tomas_fisicas_detalle_tenant ON officemart.tomas_fisicas_detalle
  FOR ALL TO authenticated
  USING (razon_social_id = officemart.app_current_tenant())
  WITH CHECK (razon_social_id = officemart.app_current_tenant());

-- ¿El almacén tiene una toma abierta? (la app pregunta antes de mover stock)
CREATE OR REPLACE FUNCTION officemart.inventario_congelado(p_almacen_id bigint)
RETURNS boolean
LANGUAGE sql
SECURITY INVOKER
SET search_path = officemart
AS $$
  SELECT EXISTS (
    SELECT 1 FROM officemart.tomas_fisicas t
    WHERE t.almacen_id = p_almacen_id
      AND t.estado = 'Abierta'
      AND t.razon_social_id = officemart.app_current_tenant()
  );
$$;
REVOKE ALL ON FUNCTION officemart.inventario_congelado(bigint) FROM public;
GRANT EXECUTE ON FUNCTION officemart.inventario_congelado(bigint) TO authenticated;

-- Red de seguridad: ningún movimiento de kardex entra a un almacén congelado.
CREATE OR REPLACE FUNCTION officemart.tg_bloquear_inventario_congelado()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = officemart
AS $$
BEGIN
  IF NEW.almacen_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM officemart.tomas_fisicas t
    WHERE t.almacen_id = NEW.almacen_id
      AND t.estado = 'Abierta'
      AND t.razon_social_id = NEW.razon_social_id
  ) THEN
    RAISE EXCEPTION 'INVENTARIO_CONGELADO: el almacen % tiene una toma fisica abierta', NEW.almacen_id;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_inventario_congelado ON officemart.transacciones_inventario;
CREATE TRIGGER trg_inventario_congelado
  BEFORE INSERT ON officemart.transacciones_inventario
  FOR EACH ROW EXECUTE FUNCTION officemart.tg_bloquear_inventario_congelado();

INSERT INTO officemart.modulos (nombre) VALUES ('Toma Física') ON CONFLICT (nombre) DO NOTHING;

NOTIFY pgrst, 'reload schema';
